// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type AddPermissionsPermissions struct {
	// The id of the permission. Provide either `id` or `name`. If both are provided `id` is used.
	ID *string `json:"id,omitempty"`
	// Identify the permission via its name. Provide either `id` or `name`. If both are provided `id` is used.
	Name *string `json:"name,omitempty"`
	// Set to true to automatically create the permissions they do not exist yet. Only works when specifying `name`.
	//               Autocreating permissions requires your root key to have the `rbac.*.create_permission` permission, otherwise the request will get rejected
	Create *bool `json:"create,omitempty"`
}

func (o *AddPermissionsPermissions) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddPermissionsPermissions) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AddPermissionsPermissions) GetCreate() *bool {
	if o == nil {
		return nil
	}
	return o.Create
}

type AddPermissionsRequestBody struct {
	// The id of the key.
	KeyID string `json:"keyId"`
	// The permissions you want to add to this key
	Permissions []AddPermissionsPermissions `json:"permissions"`
}

func (o *AddPermissionsRequestBody) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

func (o *AddPermissionsRequestBody) GetPermissions() []AddPermissionsPermissions {
	if o == nil {
		return []AddPermissionsPermissions{}
	}
	return o.Permissions
}

type ResponseBody struct {
	// The id of the permission. This is used internally
	ID string `json:"id"`
	// The name of the permission
	Name string `json:"name"`
}

func (o *ResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

type AddPermissionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// All currently connected permissions
	ResponseBodies []ResponseBody
}

func (o *AddPermissionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AddPermissionsResponse) GetResponseBodies() []ResponseBody {
	if o == nil {
		return nil
	}
	return o.ResponseBodies
}
