// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type AddRolesRoles struct {
	// The id of the role. Provide either `id` or `name`. If both are provided `id` is used.
	ID *string `json:"id,omitempty"`
	// Identify the role via its name. Provide either `id` or `name`. If both are provided `id` is used.
	Name *string `json:"name,omitempty"`
	// Set to true to automatically create the permissions they do not exist yet. Only works when specifying `name`.
	//               Autocreating roles requires your root key to have the `rbac.*.create_role` permission, otherwise the request will get rejected
	Create *bool `json:"create,omitempty"`
}

func (o *AddRolesRoles) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddRolesRoles) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AddRolesRoles) GetCreate() *bool {
	if o == nil {
		return nil
	}
	return o.Create
}

type AddRolesRequestBody struct {
	// The id of the key.
	KeyID string `json:"keyId"`
	// The roles you want to set for this key. This overwrites all existing roles.
	//           Setting roles requires the `rbac.*.add_role_to_key` permission.
	Roles []AddRolesRoles `json:"roles"`
}

func (o *AddRolesRequestBody) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

func (o *AddRolesRequestBody) GetRoles() []AddRolesRoles {
	if o == nil {
		return []AddRolesRoles{}
	}
	return o.Roles
}

type AddRolesResponseBody struct {
	// The id of the role. This is used internally
	ID string `json:"id"`
	// The name of the role
	Name string `json:"name"`
}

func (o *AddRolesResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AddRolesResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

type AddRolesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// All currently connected roles
	ResponseBodies []AddRolesResponseBody
}

func (o *AddRolesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AddRolesResponse) GetResponseBodies() []AddRolesResponseBody {
	if o == nil {
		return nil
	}
	return o.ResponseBodies
}
