// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type CreatePermissionRequestBody struct {
	// The unique name of your permission.
	Name string `json:"name"`
	// Explain what this permission does. This is just for your team, your users will not see this.
	Description *string `json:"description,omitempty"`
}

func (o *CreatePermissionRequestBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreatePermissionRequestBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

// CreatePermissionResponseBody - Sucessfully created a permission
type CreatePermissionResponseBody struct {
	// The id of the permission. This is used internally
	PermissionID string `json:"permissionId"`
}

func (o *CreatePermissionResponseBody) GetPermissionID() string {
	if o == nil {
		return ""
	}
	return o.PermissionID
}

type CreatePermissionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Sucessfully created a permission
	Object *CreatePermissionResponseBody
}

func (o *CreatePermissionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatePermissionResponse) GetObject() *CreatePermissionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
