// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type CreateRoleRequestBody struct {
	// The unique name of your role.
	Name string `json:"name"`
	// Explain what this role does. This is just for your team, your users will not see this.
	Description *string `json:"description,omitempty"`
}

func (o *CreateRoleRequestBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateRoleRequestBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

// CreateRoleResponseBody - Sucessfully created a role
type CreateRoleResponseBody struct {
	// The id of the role. This is used internally
	RoleID string `json:"roleId"`
}

func (o *CreateRoleResponseBody) GetRoleID() string {
	if o == nil {
		return ""
	}
	return o.RoleID
}

type CreateRoleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Sucessfully created a role
	Object *CreateRoleResponseBody
}

func (o *CreateRoleResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateRoleResponse) GetObject() *CreateRoleResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
