// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type DeleteRoleRequestBody struct {
	// The id of the role you want to delete.
	RoleID string `json:"roleId"`
}

func (o *DeleteRoleRequestBody) GetRoleID() string {
	if o == nil {
		return ""
	}
	return o.RoleID
}

// DeleteRoleResponseBody - Sucessfully deleted a role
type DeleteRoleResponseBody struct {
}

type DeleteRoleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Sucessfully deleted a role
	Object *DeleteRoleResponseBody
}

func (o *DeleteRoleResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteRoleResponse) GetObject() *DeleteRoleResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
