// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type DeleteeIdentityRequestBody struct {
	// The id of the identity to delete
	IdentityID string `json:"identityId"`
}

func (o *DeleteeIdentityRequestBody) GetIdentityID() string {
	if o == nil {
		return ""
	}
	return o.IdentityID
}

// DeleteeIdentityResponseBody - The identity was successfully deleted, it may take up to 30s for this to take effect in all regions
type DeleteeIdentityResponseBody struct {
}

type DeleteeIdentityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The identity was successfully deleted, it may take up to 30s for this to take effect in all regions
	Object *DeleteeIdentityResponseBody
}

func (o *DeleteeIdentityResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteeIdentityResponse) GetObject() *DeleteeIdentityResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
