// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type GetAPIRequest struct {
	APIID string `queryParam:"style=form,explode=true,name=apiId"`
}

func (o *GetAPIRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

// GetAPIResponseBody - The configuration for an api
type GetAPIResponseBody struct {
	// The id of the key
	ID string `json:"id"`
	// The id of the workspace that owns the api
	WorkspaceID string `json:"workspaceId"`
	// The name of the api. This is internal and your users will not see this.
	Name *string `json:"name,omitempty"`
}

func (o *GetAPIResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetAPIResponseBody) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *GetAPIResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type GetAPIResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The configuration for an api
	Object *GetAPIResponseBody
}

func (o *GetAPIResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAPIResponse) GetObject() *GetAPIResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
