// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type GetPermissionRequest struct {
	PermissionID string `queryParam:"style=form,explode=true,name=permissionId"`
}

func (o *GetPermissionRequest) GetPermissionID() string {
	if o == nil {
		return ""
	}
	return o.PermissionID
}

// GetPermissionResponseBody - The Role
type GetPermissionResponseBody struct {
	// The id of the permission
	ID string `json:"id"`
	// The name of the permission.
	Name string `json:"name"`
	// The description of what this permission does. This is just for your team, your users will not see this.
	Description *string `json:"description,omitempty"`
}

func (o *GetPermissionResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetPermissionResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GetPermissionResponseBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

type GetPermissionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Role
	Object *GetPermissionResponseBody
}

func (o *GetPermissionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetPermissionResponse) GetObject() *GetPermissionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
