// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type GetRoleRequest struct {
	RoleID string `queryParam:"style=form,explode=true,name=roleId"`
}

func (o *GetRoleRequest) GetRoleID() string {
	if o == nil {
		return ""
	}
	return o.RoleID
}

// GetRoleResponseBody - The Role
type GetRoleResponseBody struct {
	// The id of the role
	ID string `json:"id"`
	// The name of the role.
	Name string `json:"name"`
	// The description of what this role does. This is just for your team, your users will not see this.
	Description *string `json:"description,omitempty"`
}

func (o *GetRoleResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetRoleResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GetRoleResponseBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

type GetRoleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Role
	Object *GetRoleResponseBody
}

func (o *GetRoleResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetRoleResponse) GetObject() *GetRoleResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
