// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type ListPermissionsResponseBody struct {
	// The id of the permission
	ID string `json:"id"`
	// The name of the permission.
	Name string `json:"name"`
	// The description of what this permission does. This is just for your team, your users will not see this.
	Description *string `json:"description,omitempty"`
}

func (o *ListPermissionsResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListPermissionsResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ListPermissionsResponseBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

type ListPermissionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The permissions in your workspace
	ResponseBodies []ListPermissionsResponseBody
}

func (o *ListPermissionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListPermissionsResponse) GetResponseBodies() []ListPermissionsResponseBody {
	if o == nil {
		return nil
	}
	return o.ResponseBodies
}
