// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type ListRolesResponseBody struct {
	// The id of the role
	ID string `json:"id"`
	// The name of the role.
	Name string `json:"name"`
	// The description of what this role does. This is just for your team, your users will not see this.
	Description *string `json:"description,omitempty"`
}

func (o *ListRolesResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListRolesResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ListRolesResponseBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

type ListRolesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Roles in your workspace
	ResponseBodies []ListRolesResponseBody
}

func (o *ListRolesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListRolesResponse) GetResponseBodies() []ListRolesResponseBody {
	if o == nil {
		return nil
	}
	return o.ResponseBodies
}
