// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/internal/utils"
	"github.com/unkeyed/unkey-go/models/components"
)

type ListOverridesRequest struct {
	NamespaceID   *string `queryParam:"style=form,explode=true,name=namespaceId"`
	NamespaceName *string `queryParam:"style=form,explode=true,name=namespaceName"`
	Limit         *int64  `default:"100" queryParam:"style=form,explode=true,name=limit"`
	Cursor        *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListOverridesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOverridesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListOverridesRequest) GetNamespaceID() *string {
	if o == nil {
		return nil
	}
	return o.NamespaceID
}

func (o *ListOverridesRequest) GetNamespaceName() *string {
	if o == nil {
		return nil
	}
	return o.NamespaceName
}

func (o *ListOverridesRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListOverridesRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type Overrides struct {
	ID         string `json:"id"`
	Identifier string `json:"identifier"`
	Limit      int64  `json:"limit"`
	Duration   int64  `json:"duration"`
	Async      *bool  `json:"async,omitempty"`
}

func (o *Overrides) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Overrides) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *Overrides) GetLimit() int64 {
	if o == nil {
		return 0
	}
	return o.Limit
}

func (o *Overrides) GetDuration() int64 {
	if o == nil {
		return 0
	}
	return o.Duration
}

func (o *Overrides) GetAsync() *bool {
	if o == nil {
		return nil
	}
	return o.Async
}

// ListOverridesResponseBody - List of overrides for the given namespace.
type ListOverridesResponseBody struct {
	Overrides []Overrides `json:"overrides"`
	// The cursor to use for the next page of results, if no cursor is returned, there are no more results
	Cursor *string `json:"cursor,omitempty"`
	// The total number of overrides for the namespace
	Total int64 `json:"total"`
}

func (o *ListOverridesResponseBody) GetOverrides() []Overrides {
	if o == nil {
		return []Overrides{}
	}
	return o.Overrides
}

func (o *ListOverridesResponseBody) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ListOverridesResponseBody) GetTotal() int64 {
	if o == nil {
		return 0
	}
	return o.Total
}

type ListOverridesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of overrides for the given namespace.
	Object *ListOverridesResponseBody
}

func (o *ListOverridesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListOverridesResponse) GetObject() *ListOverridesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
