// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/internal/utils"
	"github.com/unkeyed/unkey-go/models/components"
)

type ListKeysRequest struct {
	APIID               string  `queryParam:"style=form,explode=true,name=apiId"`
	Limit               *int64  `default:"100" queryParam:"style=form,explode=true,name=limit"`
	Cursor              *string `queryParam:"style=form,explode=true,name=cursor"`
	OwnerID             *string `queryParam:"style=form,explode=true,name=ownerId"`
	ExternalID          *string `queryParam:"style=form,explode=true,name=externalId"`
	Decrypt             *bool   `queryParam:"style=form,explode=true,name=decrypt"`
	RevalidateKeysCache *bool   `default:"false" queryParam:"style=form,explode=true,name=revalidateKeysCache"`
}

func (l ListKeysRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListKeysRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListKeysRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *ListKeysRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListKeysRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ListKeysRequest) GetOwnerID() *string {
	if o == nil {
		return nil
	}
	return o.OwnerID
}

func (o *ListKeysRequest) GetExternalID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalID
}

func (o *ListKeysRequest) GetDecrypt() *bool {
	if o == nil {
		return nil
	}
	return o.Decrypt
}

func (o *ListKeysRequest) GetRevalidateKeysCache() *bool {
	if o == nil {
		return nil
	}
	return o.RevalidateKeysCache
}

// ListKeysResponseBody - List of keys for the api
type ListKeysResponseBody struct {
	Keys []components.Key `json:"keys"`
	// The cursor to use for the next page of results, if no cursor is returned, there are no more results
	Cursor *string `json:"cursor,omitempty"`
	// The total number of keys for this api. This is an approximation and may lag behind up to 5 minutes.
	Total int64 `json:"total"`
}

func (o *ListKeysResponseBody) GetKeys() []components.Key {
	if o == nil {
		return []components.Key{}
	}
	return o.Keys
}

func (o *ListKeysResponseBody) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ListKeysResponseBody) GetTotal() int64 {
	if o == nil {
		return 0
	}
	return o.Total
}

type ListKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of keys for the api
	Object *ListKeysResponseBody
}

func (o *ListKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListKeysResponse) GetObject() *ListKeysResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
