// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type RemovePermissionsPermissions struct {
	// The id of the permission. Provide either `id` or `name`. If both are provided `id` is used.
	ID *string `json:"id,omitempty"`
	// Identify the permission via its name. Provide either `id` or `name`. If both are provided `id` is used.
	Name *string `json:"name,omitempty"`
}

func (o *RemovePermissionsPermissions) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *RemovePermissionsPermissions) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type RemovePermissionsRequestBody struct {
	// The id of the key.
	KeyID string `json:"keyId"`
	// The permissions you want to remove from this key.
	Permissions []RemovePermissionsPermissions `json:"permissions"`
}

func (o *RemovePermissionsRequestBody) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

func (o *RemovePermissionsRequestBody) GetPermissions() []RemovePermissionsPermissions {
	if o == nil {
		return []RemovePermissionsPermissions{}
	}
	return o.Permissions
}

// RemovePermissionsResponseBody - Success
type RemovePermissionsResponseBody struct {
}

type RemovePermissionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *RemovePermissionsResponseBody
}

func (o *RemovePermissionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RemovePermissionsResponse) GetObject() *RemovePermissionsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
