// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unkeyed/unkey-go/models/components"
)

type RemoveRolesRoles struct {
	// The id of the role. Provide either `id` or `name`. If both are provided `id` is used.
	ID *string `json:"id,omitempty"`
	// Identify the role via its name. Provide either `id` or `name`. If both are provided `id` is used.
	Name *string `json:"name,omitempty"`
}

func (o *RemoveRolesRoles) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *RemoveRolesRoles) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type RemoveRolesRequestBody struct {
	// The id of the key.
	KeyID string `json:"keyId"`
	// The roles you want to remove from this key.
	Roles []RemoveRolesRoles `json:"roles"`
}

func (o *RemoveRolesRequestBody) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

func (o *RemoveRolesRequestBody) GetRoles() []RemoveRolesRoles {
	if o == nil {
		return []RemoveRolesRoles{}
	}
	return o.Roles
}

// RemoveRolesResponseBody - Success
type RemoveRolesResponseBody struct {
}

type RemoveRolesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *RemoveRolesResponseBody
}

func (o *RemoveRolesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RemoveRolesResponse) GetObject() *RemoveRolesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
