// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/unkeyed/unkey-go/internal/utils"
	"github.com/unkeyed/unkey-go/models/components"
)

type Permissions2 struct {
	// The name of the permission
	Name string `json:"name"`
}

func (o *Permissions2) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

type Permissions1 struct {
	// The id of the permission.
	ID string `json:"id"`
}

func (o *Permissions1) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type RemovePermissionsPermissionsType string

const (
	RemovePermissionsPermissionsTypePermissions1 RemovePermissionsPermissionsType = "permissions_1"
	RemovePermissionsPermissionsTypePermissions2 RemovePermissionsPermissionsType = "permissions_2"
)

type RemovePermissionsPermissions struct {
	Permissions1 *Permissions1
	Permissions2 *Permissions2

	Type RemovePermissionsPermissionsType
}

func CreateRemovePermissionsPermissionsPermissions1(permissions1 Permissions1) RemovePermissionsPermissions {
	typ := RemovePermissionsPermissionsTypePermissions1

	return RemovePermissionsPermissions{
		Permissions1: &permissions1,
		Type:         typ,
	}
}

func CreateRemovePermissionsPermissionsPermissions2(permissions2 Permissions2) RemovePermissionsPermissions {
	typ := RemovePermissionsPermissionsTypePermissions2

	return RemovePermissionsPermissions{
		Permissions2: &permissions2,
		Type:         typ,
	}
}

func (u *RemovePermissionsPermissions) UnmarshalJSON(data []byte) error {

	var permissions1 Permissions1 = Permissions1{}
	if err := utils.UnmarshalJSON(data, &permissions1, "", true, true); err == nil {
		u.Permissions1 = &permissions1
		u.Type = RemovePermissionsPermissionsTypePermissions1
		return nil
	}

	var permissions2 Permissions2 = Permissions2{}
	if err := utils.UnmarshalJSON(data, &permissions2, "", true, true); err == nil {
		u.Permissions2 = &permissions2
		u.Type = RemovePermissionsPermissionsTypePermissions2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RemovePermissionsPermissions", string(data))
}

func (u RemovePermissionsPermissions) MarshalJSON() ([]byte, error) {
	if u.Permissions1 != nil {
		return utils.MarshalJSON(u.Permissions1, "", true)
	}

	if u.Permissions2 != nil {
		return utils.MarshalJSON(u.Permissions2, "", true)
	}

	return nil, errors.New("could not marshal union type RemovePermissionsPermissions: all fields are null")
}

type RemovePermissionsRequestBody struct {
	// The id of the key.
	KeyID string `json:"keyId"`
	// The permissions you want to remove from this key
	Permissions []RemovePermissionsPermissions `json:"permissions"`
}

func (o *RemovePermissionsRequestBody) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

func (o *RemovePermissionsRequestBody) GetPermissions() []RemovePermissionsPermissions {
	if o == nil {
		return []RemovePermissionsPermissions{}
	}
	return o.Permissions
}

// RemovePermissionsResponseBody - Success
type RemovePermissionsResponseBody struct {
}

type RemovePermissionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *RemovePermissionsResponseBody
}

func (o *RemovePermissionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RemovePermissionsResponse) GetObject() *RemovePermissionsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
