// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// ErrDeleteProtectedCode - A machine readable error code.
type ErrDeleteProtectedCode string

const (
	ErrDeleteProtectedCodeDeleteProtected ErrDeleteProtectedCode = "DELETE_PROTECTED"
)

func (e ErrDeleteProtectedCode) ToPointer() *ErrDeleteProtectedCode {
	return &e
}
func (e *ErrDeleteProtectedCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DELETE_PROTECTED":
		*e = ErrDeleteProtectedCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrDeleteProtectedCode: %v", v)
	}
}

type ErrDeleteProtectedError struct {
	// A machine readable error code.
	Code ErrDeleteProtectedCode `json:"code"`
	// A link to our documentation with more details about this error code
	Docs string `json:"docs"`
	// A human readable explanation of what went wrong
	Message string `json:"message"`
	// Please always include the requestId in your error report
	RequestID string `json:"requestId"`
}

func (o *ErrDeleteProtectedError) GetCode() ErrDeleteProtectedCode {
	if o == nil {
		return ErrDeleteProtectedCode("")
	}
	return o.Code
}

func (o *ErrDeleteProtectedError) GetDocs() string {
	if o == nil {
		return ""
	}
	return o.Docs
}

func (o *ErrDeleteProtectedError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *ErrDeleteProtectedError) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

type ErrDeleteProtected struct {
	Error_ ErrDeleteProtectedError `json:"error"`
}

var _ error = &ErrDeleteProtected{}

func (e *ErrDeleteProtected) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
