// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// ErrPreconditionFailedCode - A machine readable error code.
type ErrPreconditionFailedCode string

const (
	ErrPreconditionFailedCodePreconditionFailed ErrPreconditionFailedCode = "PRECONDITION_FAILED"
)

func (e ErrPreconditionFailedCode) ToPointer() *ErrPreconditionFailedCode {
	return &e
}
func (e *ErrPreconditionFailedCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PRECONDITION_FAILED":
		*e = ErrPreconditionFailedCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrPreconditionFailedCode: %v", v)
	}
}

type ErrPreconditionFailedError struct {
	// A machine readable error code.
	Code ErrPreconditionFailedCode `json:"code"`
	// A link to our documentation with more details about this error code
	Docs string `json:"docs"`
	// A human readable explanation of what went wrong
	Message string `json:"message"`
	// Please always include the requestId in your error report
	RequestID string `json:"requestId"`
}

func (o *ErrPreconditionFailedError) GetCode() ErrPreconditionFailedCode {
	if o == nil {
		return ErrPreconditionFailedCode("")
	}
	return o.Code
}

func (o *ErrPreconditionFailedError) GetDocs() string {
	if o == nil {
		return ""
	}
	return o.Docs
}

func (o *ErrPreconditionFailedError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *ErrPreconditionFailedError) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

type ErrPreconditionFailed struct {
	Error_ ErrPreconditionFailedError `json:"error"`
}

var _ error = &ErrPreconditionFailed{}

func (e *ErrPreconditionFailed) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
